{
 "title": "RVK dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Project",
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "content": "<center><img src=\"http://localhost:8888/n5geh_logo.png\" width=\"200\" /></center>"
  },
  { "title": "schema of the RVPP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "schema of the RVPP",
   "type": "text",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 6 },
   "content": "<center><img src=\"http://localhost:8888/RVK_plant_scheme.png\" /></center>"
  },
  {
   "title": "general",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status of devices",
     "type": "graph",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  boiler_status AS \"gas boiler\"\nFROM  mtopeniot.etrvk\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  chp_status AS \"chp unit\"\nFROM  mtopeniot.etrvk\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  elctric_heater_status AS \"electric heater\"\nFROM  mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Total electricity production in kW",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  -wh03_mainmeter AS \"Q_el_tot_in_kW\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Total electricity production in kWh",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 16, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum(-wh03_mainmeter*10.0/3600.0) AS \"Q_el_rod_in_kW\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Electricity consumption by users in kW",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum(wh03_mainmeter-wh02_heaterrod-wh01_heatsources) AS \"Q_el_users_in_kW\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Total electricity used by users in kWh",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 16, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum((wh03_mainmeter-wh02_heaterrod-wh01_heatsources)*10.0/3600.0) AS \"Q_el_tot_usr_in_kWh\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Heat consumption in kW",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  (v01_colddrinkingwater*(t21_domestichotwater-t22_domesticcoldwater)+v02_heatingcircuit*(t25_supply_heatingcircuit-t24_return_heatingcircuit))*1000.0*4.2 AS \"Q_heat_tot_in_kW\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Total heat consumed in kWh",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 16, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum((v01_colddrinkingwater*(t21_domestichotwater-t22_domesticcoldwater)+v02_heatingcircuit*(t25_supply_heatingcircuit-t24_return_heatingcircuit))*1000.0*4.2*10.0/3600.0) AS \"Q_el_src_in_kW\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Total heat production in kW",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 13 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  ((t26_supply_chpunit-t27_return_chpunit)*v03_chpunit+(t28_supply_gasboiler-t29_return_gasboiler)*v04_gasboiler)*1000.0*4.2 AS \"Q_heat_tot_in_kW\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Total heat produced in kWh",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 16, "y": 13 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum(((t26_supply_chpunit-t27_return_chpunit)*v03_chpunit+(t28_supply_gasboiler-t29_return_gasboiler)*v04_gasboiler)*1000.0*4.2*10.0/3600.0) AS \"Q_heat_tot_in_kWh\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Total gas consumption in m3/s",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 15 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  vgas01_mainmeter AS \"Q_heat_hk_in_kW\"\nFROM  mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Gas consumed so far in m3",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 16, "y": 15 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum(vgas01_mainmeter*10.0) AS \"Q_gas_in_m3\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Volume flows in m3/s",
     "type": "graph",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  v01_colddrinkingwater AS \"domestic hot water\"\nFROM  mtopeniot.etrvk\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  v02_heatingcircuit AS \"heating circuit\"\nFROM  mtopeniot.etrvk\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  v03_chpunit AS \"chp unit\"\nFROM  mtopeniot.etrvk\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  v04_gasboiler AS \"gas boiler\"\nFROM  mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Temperature in storage tank",
     "type": "bargauge",
     "gridPos": { "h": 19, "w": 7, "x": 9, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t20_sp20 AS \"t20\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t19_sp19 AS \"t19\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t18_sp18 AS \"t18\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t17_sp17 AS \"t17\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t16_sp16 AS \"t16\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t15_sp15 AS \"t15\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t14_sp14 AS \"t14\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t13_sp13 AS \"t13\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t12_sp12 AS \"t12\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t11_sp11 AS \"t11\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t10_sp10 AS \"t10\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t09_sp09 AS \"t09\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t08_sp08 AS \"t08\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t07_sp07 AS \"t07\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t06_sp06 AS \"t06\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t05_sp05 AS \"t05\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t04_sp04 AS \"t04\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t03_sp03 AS \"t03\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t02_sp02 AS \"t02\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t01_sp01 AS \"t01\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Energy balance of storage in kWh",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 16, "y": 17 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum((((t28_supply_gasboiler-t29_return_gasboiler)*v04_gasboiler+(t26_supply_chpunit-t27_return_chpunit)*v03_chpunit)-(v01_colddrinkingwater*(t21_domestichotwater-t22_domesticcoldwater)+v02_heatingcircuit*(t25_supply_heatingcircuit-t24_return_heatingcircuit)))*1000.0*4.2*10.0/3600.0) AS \"Q_tank_in_kWh\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1\n"
      }
     ]
    }
   ]
  },
  {
   "title": "electricity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total electricity production in kW",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  -wh03_mainmeter AS \"Q_el_tot_in_kW\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Total electricity production in kW",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  -wh03_mainmeter AS \"Q_el_tot_in_kW\"\nFROM mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Total electricity produced in kWh",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum(-wh03_mainmeter*10.0/3600.0) AS \"Q_el_tot_in_kWh\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Electricity from CHP in kW",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  -wh01_heatsources AS \"Q_el_chp_in_kW\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Electricity produced by chp in kWh",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum((-wh01_heatsources)*10.0/3600.0) AS \"Q_dhw_in_kWh\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Heater rod consumption in kW",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  wh02_heaterrod AS \"Q_el_rod_in_kW\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Heater rod consumption in kWh",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum(wh02_heaterrod*10.0/3600.0) AS \"Q_rod_in_kWh\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Total electricity consumption in kW",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum(wh03_mainmeter-wh02_heaterrod-wh01_heatsources) AS \"Q_el_users_in_kW\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Electricity consumption by users in kW",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 13 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum(wh03_mainmeter-wh02_heaterrod-wh01_heatsources) AS \"Q_el_users_in_kW\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Total electricity used by users in kWh",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 13 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum((wh03_mainmeter-wh02_heaterrod-wh01_heatsources)*10.0/3600.0) AS \"Q_el_tot_usr_in_kWh\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1\n"
      }
     ]
    }
   ]
  },
  {
   "title": "heat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total heat production in kW",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  ((t26_supply_chpunit-t27_return_chpunit)*v03_chpunit+(t28_supply_gasboiler-t29_return_gasboiler)*v04_gasboiler)*4.2 AS \"Q_heat_tot_in_kW\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Total heat production in kW",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  ((t26_supply_chpunit-t27_return_chpunit)*v03_chpunit+(t28_supply_gasboiler-t29_return_gasboiler)*v04_gasboiler)*1000.0*4.2 AS \"Q_heat_tot_in_kW\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Total heat produced in kWh",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum(((t26_supply_chpunit-t27_return_chpunit)*v03_chpunit+(t28_supply_gasboiler-t29_return_gasboiler)*v04_gasboiler)*1000.0*4.2*10.0/3600.0) AS \"Q_heat_tot_in_kWh\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Heat production CHP in kW",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  ((t26_supply_chpunit-t27_return_chpunit)*v03_chpunit*1000.0*4.2) AS \"Q_heat_chp_in_kW\"\nFROM mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Heat produced by CHP in kWh",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum((t26_supply_chpunit-t27_return_chpunit)*1000.0*4.2*v03_chpunit*10.0/3600.0) AS \"Q_chp_in_kWh\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Heat production gas boiler in kW",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  ((t28_supply_gasboiler-t29_return_gasboiler)*v04_gasboiler*1000.0*4.2) AS \"Q_el_tot_in_kW\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Heat produced by gas boiler in kWh",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum((t28_supply_gasboiler-t29_return_gasboiler)*1000.0*4.2*v04_gasboiler*10.0/3600.0) AS \"Q_k_in_kWh\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Heat consumption in kW",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  (v01_colddrinkingwater*(t21_domestichotwater-t22_domesticcoldwater)+v02_heatingcircuit*(t25_supply_heatingcircuit-t24_return_heatingcircuit))*4.2 AS \"Q_el_rod_in_kW\"\nFROM  mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Heat consumption DHW",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 13 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  ((t21_domestichotwater-t22_domesticcoldwater)*4.2*1000.0*v01_colddrinkingwater) AS \"Q_el_tot_in_kW\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Heat consumption DHW in kWh",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 13 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum((t21_domestichotwater-t22_domesticcoldwater)*4.2*v01_colddrinkingwater*10.0/3600.0) AS \"Q_dhw_in_kWh\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Heat concumption heating system in kW",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 15 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  ((t25_supply_heatingcircuit-t24_return_heatingcircuit)*4.2*1000.0*v02_heatingcircuit) AS \"Q_heat_hk_in_kW\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Heat consumed by heating in kWh",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 15 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum(((t25_supply_heatingcircuit-t24_return_heatingcircuit)*4.2*1000.0*v02_heatingcircuit)) AS \"Q_heat_hk_in_kWh\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1\n"
      }
     ]
    }
   ]
  },
  {
   "title": "gas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total gas consumption in m3/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  vgas01_mainmeter AS \"V_gas_tot_in_m3_s\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Total gas consumption in m3/s",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  vgas01_mainmeter AS \"V_gas_tot_in_m3_s\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Total gas consumed in m3",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum(vgas01_mainmeter*10.0) AS \"Q_gas_in_m3\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Gas consumption  CHP unit",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  vgas02_chpunit AS \"V_gas_chp_m3_s\"\nFROM mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Gas consumed by CHP unit in m3",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum(vgas02_chpunit*10.0) AS \"V_gas_chp_m3\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Appliances - domestic hot water preparation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatures dhw in °C",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t21_domestichotwater AS \"hot water\"\nFROM  mtopeniot.etrvk\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t22_domesticcoldwater AS \"cold water\"\nFROM  mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Hot water temperature in DHW system in °C",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  t21_domestichotwater AS \"Q_el_tot_in_kW\"\nFROM mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Temperature of cold drinking water in °C",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  t22_domesticcoldwater AS \"t_cold_dhw_in_C\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Volumetric flow of domestic hot water in m3/s",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  v01_colddrinkingwater AS \"Q_el_tot_in_kW\"\nFROM mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Volume of used domestic hot water in m3",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum(v01_colddrinkingwater*10.0/3600.0) AS \"Q_dhw_in_kWh\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Appliances - heating system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heating system temperatures in °C",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t25_supply_heatingcircuit AS \"supply heating\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t24_return_heatingcircuit AS \"return heating\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Supply temperature in °C",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  t25_supply_heatingcircuit AS \"t_v_in_C\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Return temperature in °C",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  t24_return_heatingcircuit AS \"t_r_in_C\"\nFROM mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Volume flow in heating circuit in m3/s",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 9, "y": 12 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  v02_heatingcircuit AS \"V_2_in_m3_s\"\nFROM mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Ambient air temperature in °C",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 9, "y": 15 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  t30_ambientairtemperature AS \"t_a_in_C\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Ambient temperature in °C",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t30_ambientairtemperature AS \"t_ambient\"\nFROM  mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Apliances - CHP unit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatures CHP in °C",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t26_supply_chpunit AS \"supply CHP\"\nFROM  mtopeniot.etrvk\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t27_return_chpunit AS \"return CHP\"\nFROM  mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Supply temperature from CHP unit in °C",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  t26_supply_chpunit AS \"t_sup_chp_in_C\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Return temperature to CHP unit in °C",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 13 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  t27_return_chpunit AS \"t_ret_chp_in_C\"\nFROM mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Volume flow into CHP unit in m3/s",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 15 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  v03_chpunit AS \"V_3_chp_in_m3_s\"\nFROM mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Appliances - gas boiler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatures of gas boiler in °C",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  t28_supply_gasboiler AS \"t_supply_gb_in_C\"\nFROM mtopeniot.etrvk\nORDER BY 1\n"
      },
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  t29_return_gasboiler AS \"t_return_gb_in_C\"\nFROM mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Supply temperature from gas boiler in °C",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 12 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  t28_supply_gasboiler AS \"t_supply_gb_in_C\"\nFROM mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Return temperature to gas boiler in °C",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 14 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  t29_return_gasboiler AS \"Q_el_tot_in_kW\"\nFROM mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Volume flow through gas boiler in m3/s",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 16 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  v04_gasboiler AS \"V_flow_gb_in_m3_s\"\nFROM mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Appliances - storage tank",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature in storage tank",
     "type": "bargauge",
     "gridPos": { "h": 22, "w": 9, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t20_sp20 AS \"t20\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t19_sp19 AS \"t19\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t18_sp18 AS \"t18\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t17_sp17 AS \"t17\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t16_sp16 AS \"t16\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t15_sp15 AS \"t15\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t14_sp14 AS \"t14\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t13_sp13 AS \"t13\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t12_sp12 AS \"t12\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t11_sp11 AS \"t11\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t10_sp10 AS \"t10\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t09_sp09 AS \"t09\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t08_sp08 AS \"t08\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t07_sp07 AS \"t07\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t06_sp06 AS \"t06\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t05_sp05 AS \"t05\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t04_sp04 AS \"t04\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t03_sp03 AS \"t03\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t02_sp02 AS \"t02\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  t01_sp01 AS \"t01\"\nFROM  mtopeniot.etrvk\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Average storage temperature in °C",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 13 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  (t01_sp01+t02_sp02+t03_sp03+t04_sp04+t05_sp05+t06_sp06+t07_sp07+t08_sp08+t09_sp09+t10_sp10+t11_sp11+t12_sp12+t13_sp13+t14_sp14+t15_sp15+t16_sp16+t17_sp17+t18_sp18+t19_sp19+t20_sp20)/20.0 AS \"t_avg_storage\"\nFROM  mtopeniot.etrvk\nORDER BY 1\n"
      }
     ]
    },
    {
     "title": "Energy balance of storage in kWh",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 15 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,$__interval),\n  sum((((t28_supply_gasboiler-t29_return_gasboiler)*v04_gasboiler+(t26_supply_chpunit-t27_return_chpunit)*v03_chpunit)-(v01_colddrinkingwater*(t21_domestichotwater-t22_domesticcoldwater)+v02_heatingcircuit*(t25_supply_heatingcircuit-t24_return_heatingcircuit)))*1000.0*4.2*10.0/3600.0) AS \"Q_tank_in_kWh\"\nFROM  mtopeniot.etrvk\nGROUP BY 1\nORDER BY 1\n"
      }
     ]
    }
   ]
  }
 ]
}