# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: CrateDB
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: CrateDB
    type: postgres
    url: crate-db:5432
    database: mtopeniot
    user: crate
    secureJsonData:
      password: 
    jsonData:
      sslmode: "disable"